"""
Unit Tests for A2ASchemaResilienceAdapter
Generated by PluginForge-A2A
"""

import pytest
from a2a_resilience_adapter import A2ASchemaResilienceAdapter

def test_tier1_local_ast_normalization():
    adapter = A2ASchemaResilienceAdapter()
    sample_dirty_payload = {
        "session_id": "sess_12345\x00",
        "agent_name": "  WorkerAgent  ",
        "nullable_drift": None,
        "valid_count": 42
    }
    res = adapter.execute_resilient(sample_dirty_payload)
    assert res["status"] == "RESOLVED_LOCAL"
    assert res["source"] == "tier_1_ast_preflight"
    data = res["data"]
    assert data["session_id"] == "sess_12345"
    assert data["agent_name"] == "WorkerAgent"
    assert "nullable_drift" not in data
    assert data["valid_count"] == 42

def test_empty_payload_handling():
    adapter = A2ASchemaResilienceAdapter()
    res = adapter.execute_resilient({})
    assert res["status"] in ("RESOLVED_LOCAL", "FALLBACK_BEST_EFFORT")
